
package Assignment11.proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileManager", targetNamespace = "http://Darth_C0mp1ler/mtom")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileManager {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List&lt;java.lang.String&gt;
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://Darth_C0mp1ler/mtom", className = "Assignment11.proxy.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://Darth_C0mp1ler/mtom", className = "Assignment11.proxy.QueryResponse")
    @Action(input = "http://Darth_C0mp1ler/mtom/FileManager/queryRequest", output = "http://Darth_C0mp1ler/mtom/FileManager/queryResponse")
    public List<String> query(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Assignment11.proxy.FileModel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://Darth_C0mp1ler/mtom", className = "Assignment11.proxy.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://Darth_C0mp1ler/mtom", className = "Assignment11.proxy.DownloadResponse")
    @Action(input = "http://Darth_C0mp1ler/mtom/FileManager/downloadRequest", output = "http://Darth_C0mp1ler/mtom/FileManager/downloadResponse")
    public FileModel download(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://Darth_C0mp1ler/mtom", className = "Assignment11.proxy.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://Darth_C0mp1ler/mtom", className = "Assignment11.proxy.UploadFileResponse")
    @Action(input = "http://Darth_C0mp1ler/mtom/FileManager/uploadFileRequest", output = "http://Darth_C0mp1ler/mtom/FileManager/uploadFileResponse")
    public boolean uploadFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2);

}
