
package person.proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPersonBase", targetNamespace = "http://assignment10/person")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPersonBase {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List&lt;person.proxy.Person&gt;
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "filterBySurname", targetNamespace = "http://assignment10/person", className = "person.proxy.FilterBySurname")
    @ResponseWrapper(localName = "filterBySurnameResponse", targetNamespace = "http://assignment10/person", className = "person.proxy.FilterBySurnameResponse")
    @Action(input = "http://assignment10/person/IPersonBase/filterBySurnameRequest", output = "http://assignment10/person/IPersonBase/filterBySurnameResponse")
    public List<Person> filterBySurname(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Person> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List&lt;person.proxy.Person&gt;
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "filterByDate", targetNamespace = "http://assignment10/person", className = "person.proxy.FilterByDate")
    @ResponseWrapper(localName = "filterByDateResponse", targetNamespace = "http://assignment10/person", className = "person.proxy.FilterByDateResponse")
    @Action(input = "http://assignment10/person/IPersonBase/filterByDateRequest", output = "http://assignment10/person/IPersonBase/filterByDateResponse")
    public List<Person> filterByDate(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Person> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1);

}
